<?php
//header,nav,...
include("layout/header.php");
include("layout/left_sidebar.php");
include("layout/right_sidebar.php");
include("layout/script.php");
include("layout/topbar.php");
//body
include("page/phieumuon.php");
//footer
include("layout/footer.php");
?>